# Generated by Django 4.2 on 2023-04-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('imageUrl', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
