# Generated by Django 4.2 on 2023-05-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
