# Generated by Django 4.2 on 2023-05-29 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
