# Generated by Django 4.2 on 2023-06-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_message_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='update_from',
            field=models.TextField(default=None),
        ),
    ]
