# Generated by Django 4.2 on 2023-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_conversation_update_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='update_from',
            field=models.TextField(blank=True, null=True),
        ),
    ]
