# Generated by Django 4.2 on 2023-06-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_conversation_update_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='update_from',
        ),
    ]
