# Generated by Django 4.2 on 2023-06-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_conversation_update_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='updated_from',
            field=models.TextField(default='admin'),
            preserve_default=False,
        ),
    ]
