# Generated by Django 4.2 on 2023-06-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_conversation_updated_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='updated_from',
            field=models.TextField(default='admin'),
        ),
    ]
