# Generated by Django 4.2 on 2023-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_conversation_updated_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='updated_from',
            field=models.TextField(default='admin', null=True),
        ),
    ]
