# Generated by Django 4.2 on 2023-06-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_conversation_updated_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='updated_from',
        ),
        migrations.AddField(
            model_name='conversation',
            name='update_from',
            field=models.TextField(default='admin'),
            preserve_default=False,
        ),
    ]
