# Generated by Django 4.2 on 2023-06-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_conversation_updated_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='viewed',
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
