# Generated by Django 4.2 on 2023-06-07 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_remove_message_viewed_post_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='current_rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.post')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
