# Generated by Django 4.2 on 2023-06-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_rating_post_current_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='current_rating',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SellerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_sellers', to='api.userextra')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.userextra')),
            ],
        ),
    ]
