# Generated by Django 4.2 on 2023-06-12 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_userextra_current_rating_sellerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerrating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_sellers', to=settings.AUTH_USER_MODEL),
        ),
    ]
