# Generated by Django 4.2 on 2023-06-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_sellerrating_rated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='nr_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
