# Generated by Django 4.2 on 2023-06-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userextra_nr_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='current_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
