# Generated by Django 4.2 on 2023-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_userextra_current_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='notify_by_mail_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextra',
            name='notify_by_mail_message',
            field=models.BooleanField(default=False),
        ),
    ]
